<x-layout title="About Us">

    <form method="POST" action="/ideas">
      <!-- CSRF Token is unique, secret ID that is generated by server and issued to the unique form entry -->
      @csrf


        <div class="col-span-full">
          <label for="description" class="block text-sm/6 font-medium text-white">Create New Idea</label>
          
          <div class="mt-2">
            <textarea 
            id="description" 
            name="description" 
            rows="3" 
            class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 @error('description') outline-red-500 @else outline-gray-300 @enderror placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
            ></textarea>

            <x-forms.error name="description" />
          </div>

          <p class="mt-3 text-sm/6 text-gray-600">Write a few sentences about your idea.</p>
        </div>

        <div class="mt-6 flex items-center gap-x-6">
  
    <button type="submit" 
    class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
        Save
    </button>

  </div>
  </form>


</x-layout>